# Change these first
owner: galaxian85 # Your GitHub organization or username, where this repository lives
repo: hackmd-api-uptime # The name of this repository

sites:
  - name: HackMD
    url: https://hackmd.io
    icon: https://hackmd.io/favicon.png
  - name: HackMD Realtime
    url: https://hackmd.io/realtime-reg/statusAll
    icon: https://hackmd.io/favicon.png
  - name: HackMD API
    url: https://api.hackmd.io/v1/ping
    icon: https://hackmd.io/favicon.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.hackmd.io
  baseUrl: /hackmd-api-uptime
  logoUrl: https://hackmd.io/apple-touch-icon.png
  name: HackMD Status
  introTitle: HackMD Status Page
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /hackmd-api-uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: HackMD
      href: https://hackmd.io
  favicon: https://hackmd.io/favicon.png
  css: ":root {
    --body-background-color: rgb(51, 51, 51);
    --body-text-color: rgb(51, 51, 51);
    --card-background-color: rgb(38, 38, 38);
    --card-border-color: rgb(51, 51, 51);
    --up-border-left-color: rgb(38, 38, 38);
    --nav-current-border-bottom-color: rgb(51, 51, 51);
  }
  main {
    color: rgb(255, 255, 255);
  }
  footer {
    color: rgb(255, 255, 255);
  }
  "
  
workflowSchedule:
  responseTime: "*/3 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
